### ISSUE TITLE
Challenges Model

### ISSUE THREAD

**Issue by dkmonaghan** [sem5640-2018/challenges#5]
I noticed that the 'challenges' model in the API spec that was pushed through today may need some tweaking. There's a goal integer, but how are we specifying what metric that goal is for? e.g a Swimming challenge isn't going to be able to measure steps.

**Comment by RobertMouncer** [comment]
Well spotted.

If a goal metric were added this would resolve the problem.
A goal metric could contain steps, duration, calories burnt, etc.
Thoughts?
